// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyJf5lAJgI54dn6rCg2uewBoySB6mW0qo',
    appId: '1:727452732248:android:b7a502893ab84b7994332d',
    messagingSenderId: '727452732248',
    projectId: 'thedemo-7d9c6',
    databaseURL: 'https://thedemo-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'thedemo-7d9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVae2gq2JiOxXEvTdQdFHRtcbOeHfF3w',
    appId: '1:727452732248:ios:e130e0519cbf778994332d',
    messagingSenderId: '727452732248',
    projectId: 'thedemo-7d9c6',
    databaseURL: 'https://thedemo-7d9c6-default-rtdb.firebaseio.com',
    storageBucket: 'thedemo-7d9c6.appspot.com',
    iosBundleId: 'com.example.zmZone',
  );
}
